version: "3.9"

services:
  db:
    image: postgres:17.6
    container_name: ticket-system-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_system
    volumes:
      - ticket-system_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: ticket-system-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ticket.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  ticket-system_postgres_data:
